// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"strings"
	"text/template"

	pgs "github.com/lyft/protoc-gen-star"
	pgsgo "github.com/lyft/protoc-gen-star/lang/go"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	"go.linka.cloud/protodb/protodb"
)

func module() *mod {
	return &mod{
		ModuleBase: &pgs.ModuleBase{},
		imports:    make(map[string]struct{}),
		oneOfs:     make(map[string]struct{}),
	}
}

type mod struct {
	*pgs.ModuleBase
	ctx     pgsgo.Context
	tpl     *template.Template
	imports map[string]struct{}
	oneOfs  map[string]struct{}
}

type keyPath []pgs.Field

func (p *mod) Name() string {
	return "protodb"
}

func (p *mod) InitContext(c pgs.BuildContext) {
	p.ModuleBase.InitContext(c)
	p.ctx = pgsgo.InitContext(c.Parameters())

	tpl := template.New("protodb").Funcs(map[string]any{
		"package": p.ctx.PackageName,
		"name":    p.ctx.Name,
		"enabled": func(m pgs.Message) bool {
			var enabled bool
			m.Extension(protodb.E_Enabled, &enabled)
			return enabled
		},
		"comment": func(s string) string {
			var out string
			parts := strings.Split(s, "\n")
			for i, v := range parts {
				if i == len(parts)-1 && v == "" {
					return out
				}
				out += "//" + v + "\n"
			}
			return out
		},
	})
	p.tpl = template.Must(tpl.Parse(protodbTpl))
}

func (p *mod) Execute(targets map[string]pgs.File, _ map[string]pgs.Package) []pgs.Artifact {
	for _, f := range targets {
		var msgs []pgs.Message
		for _, m := range f.AllMessages() {
			var enabled bool
			ok, err := m.Extension(protodb.E_Enabled, &enabled)
			if err != nil {
				p.Fail(err)
			}
			if !ok || !enabled {
				continue
			}
			p.validateMessageKey(m)
			msgs = append(msgs, m)
		}
		p.generate(f, msgs)
	}
	return p.Artifacts()
}

func (p *mod) validateMessageKey(m pgs.Message) {
	keys := p.collectMessageKeys(m)
	if len(keys) == 0 {
		return
	}
	for _, path := range keys {
		leaf := path.leaf()
		if leaf.Type().IsMap() || leaf.Type().IsRepeated() || leaf.InOneOf() || leaf.Descriptor().GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			p.Failf("%s: %s: only non repeated and not oneof scalar types are supported as key, got %T", m.Name(), path.String(), leaf.Type())
		}
		for i := 0; i < len(path)-1; i++ {
			f := path[i]
			if !f.Type().IsEmbed() || f.Type().IsMap() || f.Type().IsRepeated() || f.InOneOf() {
				p.Failf("%s: %s: nested key path must traverse singular message fields", m.Name(), path.String())
			}
		}
	}
	if len(keys) == 1 {
		return
	}
	paths := make([]string, 0, len(keys))
	for _, path := range keys {
		paths = append(paths, path.String())
	}
	p.Failf("%s: multiple keys found for message: %s", m.Name(), strings.Join(paths, ", "))
}

func (p *mod) collectMessageKeys(m pgs.Message) []keyPath {
	stack := map[string]bool{m.FullyQualifiedName(): true}
	return p.collectMessageKeysIn(m, nil, stack)
}

func (p *mod) collectMessageKeysIn(m pgs.Message, path keyPath, stack map[string]bool) []keyPath {
	var out []keyPath
	for _, f := range m.Fields() {
		next := make(keyPath, 0, len(path)+1)
		next = append(next, path...)
		next = append(next, f)
		var key bool
		f.Extension(protodb.E_Key, &key)
		if key {
			out = append(out, next)
		}
		if !f.Type().IsEmbed() || f.Type().IsMap() || f.Type().IsRepeated() || f.InOneOf() {
			continue
		}
		embed := f.Type().Embed()
		if embed == nil {
			continue
		}
		name := embed.FullyQualifiedName()
		if stack[name] {
			continue
		}
		stack[name] = true
		out = append(out, p.collectMessageKeysIn(embed, next, stack)...)
		delete(stack, name)
	}
	return out
}

func (p keyPath) leaf() pgs.Field {
	return p[len(p)-1]
}

func (p keyPath) String() string {
	parts := make([]string, 0, len(p))
	for _, f := range p {
		parts = append(parts, f.Name().String())
	}
	return strings.Join(parts, ".")
}

func (p *mod) generate(f pgs.File, msgs []pgs.Message) {
	if len(msgs) == 0 {
		return
	}
	name := p.ctx.OutputPath(f).SetExt(".protodb.go")
	p.AddGeneratorTemplateFile(name.String(), p.tpl, f)
}

const protodbTpl = `{{ comment .SyntaxSourceCodeInfo.LeadingComments }}
{{ range .SyntaxSourceCodeInfo.LeadingDetachedComments }}
{{ comment . }}
{{ end }}
// Code generated by protoc-gen-protodb. DO NOT EDIT.

package {{ package . }}

import (
	"go.linka.cloud/protodb"
	"go.linka.cloud/protodb/typed"
)

{{ range .AllMessages }}

{{ if enabled . }}

type (
	{{ name . }}Store typed.Store[{{ name . }}, *{{ name . }}]
	{{ name . }}Tx typed.Tx[{{ name . }}, *{{ name . }}]
	{{ name . }}Event typed.Event[{{ name . }}, *{{ name . }}]
)

func New{{ name . }}Store(db protodb.Client) {{ name . }}Store {
	return typed.NewStore[{{ name . }}, *{{ name . }}](db)
}

func New{{ name . }}Tx(tx protodb.Tx) {{ name . }}Tx {
	return typed.NewTx[{{ name . }}, *{{ name . }}](tx)
}

{{ end }}

{{ end }}
`

func main() {
	feat := uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
	pgs.Init(
		pgs.DebugEnv("DEBUG"),
		pgs.SupportedFeatures(&feat),
	).RegisterModule(
		module(),
	).RegisterPostProcessor(
		pgsgo.GoFmt(),
	).Render()
}
