// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package pb

var OpFields = struct {
	New     string
	Set     string
	Delete  string
	Commit  string
	Discard string
}{
	New:     "new",
	Set:     "set",
	Delete:  "delete",
	Commit:  "commit",
	Discard: "discard",
}

var NewFields = struct {
	At string
}{
	At: "at",
}

var SetFields = struct {
	Key       string
	Value     string
	ExpiresAt string
}{
	Key:       "key",
	Value:     "value",
	ExpiresAt: "expires_at",
}

var DeleteFields = struct {
	Key string
}{
	Key: "key",
}

var CommitFields = struct {
}{}

var DiscardFields = struct {
}{}

var BatchFields = struct {
	TxID string
	Ops  string
}{
	TxID: "tx_id",
	Ops:  "ops",
}

var EntryFields = struct {
	Batch string
}{
	Batch: "batch",
}
