// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.0
// source: internal/token/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	LastPrefix    []byte                 `protobuf:"bytes,3,opt,name=last_prefix,json=lastPrefix,proto3" json:"last_prefix,omitempty"`
	FiltersHash   string                 `protobuf:"bytes,4,opt,name=filters_hash,json=filtersHash,proto3" json:"filters_hash,omitempty"`
	Reverse       bool                   `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	OrderHash     string                 `protobuf:"bytes,6,opt,name=order_hash,json=orderHash,proto3" json:"order_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_internal_token_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_internal_token_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_internal_token_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Token) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Token) GetLastPrefix() []byte {
	if x != nil {
		return x.LastPrefix
	}
	return nil
}

func (x *Token) GetFiltersHash() string {
	if x != nil {
		return x.FiltersHash
	}
	return ""
}

func (x *Token) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *Token) GetOrderHash() string {
	if x != nil {
		return x.OrderHash
	}
	return ""
}

var File_internal_token_token_proto protoreflect.FileDescriptor

const file_internal_token_token_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/token/token.proto\x12\"linka.cloud.protodb.internal.token\"\xa8\x01\n" +
	"\x05Token\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x04R\x02ts\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vlast_prefix\x18\x03 \x01(\fR\n" +
	"lastPrefix\x12!\n" +
	"\ffilters_hash\x18\x04 \x01(\tR\vfiltersHash\x12\x18\n" +
	"\areverse\x18\x05 \x01(\bR\areverse\x12\x1d\n" +
	"\n" +
	"order_hash\x18\x06 \x01(\tR\torderHashB-Z+go.linka.cloud/protodb/internal/token;tokenb\x06proto3"

var (
	file_internal_token_token_proto_rawDescOnce sync.Once
	file_internal_token_token_proto_rawDescData []byte
)

func file_internal_token_token_proto_rawDescGZIP() []byte {
	file_internal_token_token_proto_rawDescOnce.Do(func() {
		file_internal_token_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_token_token_proto_rawDesc), len(file_internal_token_token_proto_rawDesc)))
	})
	return file_internal_token_token_proto_rawDescData
}

var file_internal_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_token_token_proto_goTypes = []any{
	(*Token)(nil), // 0: linka.cloud.protodb.internal.token.Token
}
var file_internal_token_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_token_token_proto_init() }
func file_internal_token_token_proto_init() {
	if File_internal_token_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_token_token_proto_rawDesc), len(file_internal_token_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_token_token_proto_goTypes,
		DependencyIndexes: file_internal_token_token_proto_depIdxs,
		MessageInfos:      file_internal_token_token_proto_msgTypes,
	}.Build()
	File_internal_token_token_proto = out.File
	file_internal_token_token_proto_goTypes = nil
	file_internal_token_token_proto_depIdxs = nil
}
