// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: protodb/protodb.proto

package protodb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unique        *bool                  `protobuf:"varint,1,opt,name=unique" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_protodb_protodb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_protodb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_protodb_protodb_proto_rawDescGZIP(), []int{0}
}

func (x *Index) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

var file_protodb_protodb_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1181,
		Name:          "protodb.enabled",
		Tag:           "varint,1181,opt,name=enabled",
		Filename:      "protodb/protodb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1182,
		Name:          "protodb.static_key",
		Tag:           "bytes,1182,opt,name=static_key",
		Filename:      "protodb/protodb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1191,
		Name:          "protodb.key",
		Tag:           "varint,1191,opt,name=key",
		Filename:      "protodb/protodb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Index)(nil),
		Field:         1192,
		Name:          "protodb.index",
		Tag:           "bytes,1192,opt,name=index",
		Filename:      "protodb/protodb.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// enabled enable store generation
	//
	// optional bool enabled = 1181;
	E_Enabled = &file_protodb_protodb_proto_extTypes[0]
	// static_key is a static key for the message type
	//
	// optional string static_key = 1182;
	E_StaticKey = &file_protodb_protodb_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// key mark the field as message key
	//
	// optional bool key = 1191;
	E_Key = &file_protodb_protodb_proto_extTypes[2]
	// index mark the field as message index
	// only fields or repeated fields of the following types can be indexed:
	// - scalar types: bool, int32, int64, uint32, uint64, sint32, sint64, fixed32, fixed64, sfixed32, sfixed64, float, double, string, bytes
	// - enum types
	// - google.protobuf.Timestamp
	// - google.protobuf.Duration
	//
	// optional protodb.Index index = 1192;
	E_Index = &file_protodb_protodb_proto_extTypes[3]
)

var File_protodb_protodb_proto protoreflect.FileDescriptor

const file_protodb_protodb_proto_rawDesc = "" +
	"\n" +
	"\x15protodb/protodb.proto\x12\aprotodb\x1a google/protobuf/descriptor.proto\"\x1f\n" +
	"\x05Index\x12\x16\n" +
	"\x06unique\x18\x01 \x01(\bR\x06unique::\n" +
	"\aenabled\x12\x1f.google.protobuf.MessageOptions\x18\x9d\t \x01(\bR\aenabled:?\n" +
	"\n" +
	"static_key\x12\x1f.google.protobuf.MessageOptions\x18\x9e\t \x01(\tR\tstaticKey:0\n" +
	"\x03key\x12\x1d.google.protobuf.FieldOptions\x18\xa7\t \x01(\bR\x03key:D\n" +
	"\x05index\x12\x1d.google.protobuf.FieldOptions\x18\xa8\t \x01(\v2\x0e.protodb.IndexR\x05indexB(Z&go.linka.cloud/protodb/protodb;protodb"

var (
	file_protodb_protodb_proto_rawDescOnce sync.Once
	file_protodb_protodb_proto_rawDescData []byte
)

func file_protodb_protodb_proto_rawDescGZIP() []byte {
	file_protodb_protodb_proto_rawDescOnce.Do(func() {
		file_protodb_protodb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protodb_protodb_proto_rawDesc), len(file_protodb_protodb_proto_rawDesc)))
	})
	return file_protodb_protodb_proto_rawDescData
}

var file_protodb_protodb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protodb_protodb_proto_goTypes = []any{
	(*Index)(nil),                       // 0: protodb.Index
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
}
var file_protodb_protodb_proto_depIdxs = []int32{
	1, // 0: protodb.enabled:extendee -> google.protobuf.MessageOptions
	1, // 1: protodb.static_key:extendee -> google.protobuf.MessageOptions
	2, // 2: protodb.key:extendee -> google.protobuf.FieldOptions
	2, // 3: protodb.index:extendee -> google.protobuf.FieldOptions
	0, // 4: protodb.index:type_name -> protodb.Index
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protodb_protodb_proto_init() }
func file_protodb_protodb_proto_init() {
	if File_protodb_protodb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protodb_protodb_proto_rawDesc), len(file_protodb_protodb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_protodb_protodb_proto_goTypes,
		DependencyIndexes: file_protodb_protodb_proto_depIdxs,
		MessageInfos:      file_protodb_protodb_proto_msgTypes,
		ExtensionInfos:    file_protodb_protodb_proto_extTypes,
	}.Build()
	File_protodb_protodb_proto = out.File
	file_protodb_protodb_proto_goTypes = nil
	file_protodb_protodb_proto_depIdxs = nil
}
