// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.0
// source: internal/badgerd/replication/gossip/pb/gossip.proto

package pb

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElectionType int32

const (
	ElectionTypeNone     ElectionType = 0
	ElectionTypeSkip     ElectionType = 1
	ElectionTypeOk       ElectionType = 2
	ElectionTypeElection ElectionType = 3
	ElectionTypeLeader   ElectionType = 4
)

// Enum value maps for ElectionType.
var (
	ElectionType_name = map[int32]string{
		0: "NONE",
		1: "SKIP",
		2: "OK",
		3: "ELECTION",
		4: "LEADER",
	}
	ElectionType_value = map[string]int32{
		"NONE":     0,
		"SKIP":     1,
		"OK":       2,
		"ELECTION": 3,
		"LEADER":   4,
	}
)

func (x ElectionType) Enum() *ElectionType {
	p := new(ElectionType)
	*p = x
	return p
}

func (x ElectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_enumTypes[0].Descriptor()
}

func (ElectionType) Type() protoreflect.EnumType {
	return &file_internal_badgerd_replication_gossip_pb_gossip_proto_enumTypes[0]
}

func (x ElectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElectionType.Descriptor instead.
func (ElectionType) EnumDescriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{0}
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         uint64                 `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          uint64                 `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *InitResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*Op                  `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateRequest) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Op struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ID    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*Op_New
	//	*Op_Set
	//	*Op_Delete
	//	*Op_Commit
	Action        isOp_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *Op) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Op) GetAction() isOp_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Op) GetNew() *New {
	if x != nil {
		if x, ok := x.Action.(*Op_New); ok {
			return x.New
		}
	}
	return nil
}

func (x *Op) GetSet() *Set {
	if x != nil {
		if x, ok := x.Action.(*Op_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Op) GetDelete() *Delete {
	if x != nil {
		if x, ok := x.Action.(*Op_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Op) GetCommit() *Commit {
	if x != nil {
		if x, ok := x.Action.(*Op_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

type isOp_Action interface {
	isOp_Action()
}

type Op_New struct {
	New *New `protobuf:"bytes,2,opt,name=new,proto3,oneof"`
}

type Op_Set struct {
	Set *Set `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

type Op_Delete struct {
	Delete *Delete `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type Op_Commit struct {
	Commit *Commit `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

func (*Op_New) isOp_Action() {}

func (*Op_Set) isOp_Action() {}

func (*Op_Delete) isOp_Action() {}

func (*Op_Commit) isOp_Action() {}

type New struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            uint64                 `protobuf:"varint,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *New) Reset() {
	*x = New{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *New) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*New) ProtoMessage() {}

func (x *New) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use New.ProtoReflect.Descriptor instead.
func (*New) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *New) GetAt() uint64 {
	if x != nil {
		return x.At
	}
	return 0
}

type Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Set) Reset() {
	*x = Set{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{5}
}

func (x *Set) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Set) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Set) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{6}
}

func (x *Delete) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            uint64                 `protobuf:"varint,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{7}
}

func (x *Commit) GetAt() uint64 {
	if x != nil {
		return x.At
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{8}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ElectionType           `protobuf:"varint,1,opt,name=type,proto3,enum=linka.cloud.protodb.internal.replication.gossip.ElectionType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetType() ElectionType {
	if x != nil {
		return x.Type
	}
	return ElectionTypeNone
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GRPCPort      uint32                 `protobuf:"varint,1,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	LocalVersion  uint64                 `protobuf:"varint,2,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP(), []int{10}
}

func (x *Meta) GetGRPCPort() uint32 {
	if x != nil {
		return x.GRPCPort
	}
	return 0
}

func (x *Meta) GetLocalVersion() uint64 {
	if x != nil {
		return x.LocalVersion
	}
	return 0
}

func (x *Meta) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

var File_internal_badgerd_replication_gossip_pb_gossip_proto protoreflect.FileDescriptor

const file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDesc = "" +
	"\n" +
	"3internal/badgerd/replication/gossip/pb/gossip.proto\x12/linka.cloud.protodb.internal.replication.gossip\x1a\x0epatch/go.proto\"#\n" +
	"\vInitRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x04R\x05since\"6\n" +
	"\fInitResponse\x12\x12\n" +
	"\x04last\x18\x01 \x01(\x04R\x04last\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"Y\n" +
	"\x10ReplicateRequest\x12E\n" +
	"\x03ops\x18\x01 \x03(\v23.linka.cloud.protodb.internal.replication.gossip.OpR\x03ops\"\xd8\x02\n" +
	"\x02Op\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12H\n" +
	"\x03new\x18\x02 \x01(\v24.linka.cloud.protodb.internal.replication.gossip.NewH\x00R\x03new\x12H\n" +
	"\x03set\x18\x03 \x01(\v24.linka.cloud.protodb.internal.replication.gossip.SetH\x00R\x03set\x12Q\n" +
	"\x06delete\x18\x04 \x01(\v27.linka.cloud.protodb.internal.replication.gossip.DeleteH\x00R\x06delete\x12Q\n" +
	"\x06commit\x18\x05 \x01(\v27.linka.cloud.protodb.internal.replication.gossip.CommitH\x00R\x06commitB\b\n" +
	"\x06action\"\x15\n" +
	"\x03New\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\x04R\x02at\"L\n" +
	"\x03Set\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\texpiresAt\"\x1a\n" +
	"\x06Delete\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x18\n" +
	"\x06Commit\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\x04R\x02at\"\x05\n" +
	"\x03Ack\"\xbb\x01\n" +
	"\aMessage\x12Q\n" +
	"\x04type\x18\x01 \x01(\x0e2=.linka.cloud.protodb.internal.replication.gossip.ElectionTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\x04meta\x18\x03 \x01(\v25.linka.cloud.protodb.internal.replication.gossip.MetaR\x04meta\"\x99\x01\n" +
	"\x04Meta\x12+\n" +
	"\tgrpc_port\x18\x01 \x01(\rB\x0eʵ\x03\n" +
	"\n" +
	"\bGRPCPortR\bgrpcPort\x127\n" +
	"\rlocal_version\x18\x02 \x01(\x04B\x12ʵ\x03\x0e\n" +
	"\fLocalVersionR\flocalVersion\x12+\n" +
	"\tis_leader\x18\x03 \x01(\bB\x0eʵ\x03\n" +
	"\n" +
	"\bIsLeaderR\bisLeader*D\n" +
	"\fElectionType\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04SKIP\x10\x01\x12\x06\n" +
	"\x02OK\x10\x02\x12\f\n" +
	"\bELECTION\x10\x03\x12\n" +
	"\n" +
	"\x06LEADER\x10\x042\xa9\x04\n" +
	"\x12ReplicationService\x12\x87\x01\n" +
	"\x04Init\x12<.linka.cloud.protodb.internal.replication.gossip.InitRequest\x1a=.linka.cloud.protodb.internal.replication.gossip.InitResponse\"\x000\x01\x12\x8a\x01\n" +
	"\tReplicate\x12A.linka.cloud.protodb.internal.replication.gossip.ReplicateRequest\x1a4.linka.cloud.protodb.internal.replication.gossip.Ack\"\x00(\x010\x01\x12y\n" +
	"\x05Alive\x124.linka.cloud.protodb.internal.replication.gossip.Ack\x1a4.linka.cloud.protodb.internal.replication.gossip.Ack\"\x00(\x010\x01\x12\x80\x01\n" +
	"\bElection\x128.linka.cloud.protodb.internal.replication.gossip.Message\x1a8.linka.cloud.protodb.internal.replication.gossip.Message\"\x00B@ʵ\x03\x02\b\x01Z8go.linka.cloud/protodb/internal/replication/gossip/pb;pbb\x06proto3"

var (
	file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescOnce sync.Once
	file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescData []byte
)

func file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescGZIP() []byte {
	file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescOnce.Do(func() {
		file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDesc), len(file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDesc)))
	})
	return file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDescData
}

var file_internal_badgerd_replication_gossip_pb_gossip_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_badgerd_replication_gossip_pb_gossip_proto_goTypes = []any{
	(ElectionType)(0),        // 0: linka.cloud.protodb.internal.replication.gossip.ElectionType
	(*InitRequest)(nil),      // 1: linka.cloud.protodb.internal.replication.gossip.InitRequest
	(*InitResponse)(nil),     // 2: linka.cloud.protodb.internal.replication.gossip.InitResponse
	(*ReplicateRequest)(nil), // 3: linka.cloud.protodb.internal.replication.gossip.ReplicateRequest
	(*Op)(nil),               // 4: linka.cloud.protodb.internal.replication.gossip.Op
	(*New)(nil),              // 5: linka.cloud.protodb.internal.replication.gossip.New
	(*Set)(nil),              // 6: linka.cloud.protodb.internal.replication.gossip.Set
	(*Delete)(nil),           // 7: linka.cloud.protodb.internal.replication.gossip.Delete
	(*Commit)(nil),           // 8: linka.cloud.protodb.internal.replication.gossip.Commit
	(*Ack)(nil),              // 9: linka.cloud.protodb.internal.replication.gossip.Ack
	(*Message)(nil),          // 10: linka.cloud.protodb.internal.replication.gossip.Message
	(*Meta)(nil),             // 11: linka.cloud.protodb.internal.replication.gossip.Meta
}
var file_internal_badgerd_replication_gossip_pb_gossip_proto_depIdxs = []int32{
	4,  // 0: linka.cloud.protodb.internal.replication.gossip.ReplicateRequest.ops:type_name -> linka.cloud.protodb.internal.replication.gossip.Op
	5,  // 1: linka.cloud.protodb.internal.replication.gossip.Op.new:type_name -> linka.cloud.protodb.internal.replication.gossip.New
	6,  // 2: linka.cloud.protodb.internal.replication.gossip.Op.set:type_name -> linka.cloud.protodb.internal.replication.gossip.Set
	7,  // 3: linka.cloud.protodb.internal.replication.gossip.Op.delete:type_name -> linka.cloud.protodb.internal.replication.gossip.Delete
	8,  // 4: linka.cloud.protodb.internal.replication.gossip.Op.commit:type_name -> linka.cloud.protodb.internal.replication.gossip.Commit
	0,  // 5: linka.cloud.protodb.internal.replication.gossip.Message.type:type_name -> linka.cloud.protodb.internal.replication.gossip.ElectionType
	11, // 6: linka.cloud.protodb.internal.replication.gossip.Message.meta:type_name -> linka.cloud.protodb.internal.replication.gossip.Meta
	1,  // 7: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Init:input_type -> linka.cloud.protodb.internal.replication.gossip.InitRequest
	3,  // 8: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Replicate:input_type -> linka.cloud.protodb.internal.replication.gossip.ReplicateRequest
	9,  // 9: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Alive:input_type -> linka.cloud.protodb.internal.replication.gossip.Ack
	10, // 10: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Election:input_type -> linka.cloud.protodb.internal.replication.gossip.Message
	2,  // 11: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Init:output_type -> linka.cloud.protodb.internal.replication.gossip.InitResponse
	9,  // 12: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Replicate:output_type -> linka.cloud.protodb.internal.replication.gossip.Ack
	9,  // 13: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Alive:output_type -> linka.cloud.protodb.internal.replication.gossip.Ack
	10, // 14: linka.cloud.protodb.internal.replication.gossip.ReplicationService.Election:output_type -> linka.cloud.protodb.internal.replication.gossip.Message
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_badgerd_replication_gossip_pb_gossip_proto_init() }
func file_internal_badgerd_replication_gossip_pb_gossip_proto_init() {
	if File_internal_badgerd_replication_gossip_pb_gossip_proto != nil {
		return
	}
	file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes[3].OneofWrappers = []any{
		(*Op_New)(nil),
		(*Op_Set)(nil),
		(*Op_Delete)(nil),
		(*Op_Commit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDesc), len(file_internal_badgerd_replication_gossip_pb_gossip_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_badgerd_replication_gossip_pb_gossip_proto_goTypes,
		DependencyIndexes: file_internal_badgerd_replication_gossip_pb_gossip_proto_depIdxs,
		EnumInfos:         file_internal_badgerd_replication_gossip_pb_gossip_proto_enumTypes,
		MessageInfos:      file_internal_badgerd_replication_gossip_pb_gossip_proto_msgTypes,
	}.Build()
	File_internal_badgerd_replication_gossip_pb_gossip_proto = out.File
	file_internal_badgerd_replication_gossip_pb_gossip_proto_goTypes = nil
	file_internal_badgerd_replication_gossip_pb_gossip_proto_depIdxs = nil
}
