// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/registry/pb/test.proto

package testprotos

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Message1 with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message1) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message1 with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Message1MultiError, or nil
// if none found.
func (m *Message1) ValidateAll() error {
	return m.validate(true)
}

func (m *Message1) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Message1MultiError(errors)
	}

	return nil
}

// Message1MultiError is an error wrapping multiple validation errors returned
// by Message1.ValidateAll() if the designated constraints aren't met.
type Message1MultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Message1MultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Message1MultiError) AllErrors() []error { return m }

// Message1ValidationError is the validation error returned by
// Message1.Validate if the designated constraints aren't met.
type Message1ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Message1ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Message1ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Message1ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Message1ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Message1ValidationError) ErrorName() string { return "Message1ValidationError" }

// Error satisfies the builtin error interface
func (e Message1ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage1.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Message1ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Message1ValidationError{}

// Validate checks the field values on Message2 with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message2) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message2 with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Message2MultiError, or nil
// if none found.
func (m *Message2) ValidateAll() error {
	return m.validate(true)
}

func (m *Message2) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Message2MultiError(errors)
	}

	return nil
}

// Message2MultiError is an error wrapping multiple validation errors returned
// by Message2.ValidateAll() if the designated constraints aren't met.
type Message2MultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Message2MultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Message2MultiError) AllErrors() []error { return m }

// Message2ValidationError is the validation error returned by
// Message2.Validate if the designated constraints aren't met.
type Message2ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Message2ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Message2ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Message2ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Message2ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Message2ValidationError) ErrorName() string { return "Message2ValidationError" }

// Error satisfies the builtin error interface
func (e Message2ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage2.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Message2ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Message2ValidationError{}

// Validate checks the field values on Message3 with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message3) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message3 with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Message3MultiError, or nil
// if none found.
func (m *Message3) ValidateAll() error {
	return m.validate(true)
}

func (m *Message3) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Message3MultiError(errors)
	}

	return nil
}

// Message3MultiError is an error wrapping multiple validation errors returned
// by Message3.ValidateAll() if the designated constraints aren't met.
type Message3MultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Message3MultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Message3MultiError) AllErrors() []error { return m }

// Message3ValidationError is the validation error returned by
// Message3.Validate if the designated constraints aren't met.
type Message3ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Message3ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Message3ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Message3ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Message3ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Message3ValidationError) ErrorName() string { return "Message3ValidationError" }

// Error satisfies the builtin error interface
func (e Message3ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage3.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Message3ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Message3ValidationError{}

// Validate checks the field values on Message4 with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message4) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message4 with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Message4MultiError, or nil
// if none found.
func (m *Message4) ValidateAll() error {
	return m.validate(true)
}

func (m *Message4) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BoolField

	if len(errors) > 0 {
		return Message4MultiError(errors)
	}

	return nil
}

// Message4MultiError is an error wrapping multiple validation errors returned
// by Message4.ValidateAll() if the designated constraints aren't met.
type Message4MultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Message4MultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Message4MultiError) AllErrors() []error { return m }

// Message4ValidationError is the validation error returned by
// Message4.Validate if the designated constraints aren't met.
type Message4ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Message4ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Message4ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Message4ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Message4ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Message4ValidationError) ErrorName() string { return "Message4ValidationError" }

// Error satisfies the builtin error interface
func (e Message4ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage4.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Message4ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Message4ValidationError{}
