// Different proto type definitions for testing the Types registry.

// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package testprotos

var Message1Fields = struct {
}{}

var Message2Fields = struct {
}{}

var Message3Fields = struct {
}{}

var Message4Fields = struct {
	BoolField string
}{
	BoolField: "bool_field",
}
